#ifndef __Mock_Top__
#define __Mock_Top__

#include "emulator.h"

class Mock_Top_t : public mod_t {
 private:
  val_t __rand_seed;
  void __srand(val_t seed) { __rand_seed = seed; }
  val_t __rand_val() { return ::__rand_val(&__rand_seed); }
 public:
  dat_t<1> Mock_Top_soc_cpu_cpath__io_ctrl_alu_b_sel;
  dat_t<1> Mock_Top_soc_cpu_dpath__io_alu_b_sel;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_bus_we;
  dat_t<1> Mock_Top_soc_cpu__io_bus_we;
  dat_t<1> Mock_Top_soc_dev__io_bus_we;
  dat_t<1> Mock_Top_soc_dev_bus__io_from_cpu_we;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_4_we;
  dat_t<1> Mock_Top_soc_dev_seven_seg__io_bus_we;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_bus_sel;
  dat_t<1> Mock_Top_soc_cpu__io_bus_sel;
  dat_t<1> Mock_Top_soc_dev__io_bus_sel;
  dat_t<1> Mock_Top_soc_dev_bus__io_from_cpu_sel;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_4_sel;
  dat_t<1> Mock_Top_soc_dev_seven_seg__io_bus_sel;
  dat_t<1> reset;
  dat_t<1> Mock_Top_soc__reset;
  dat_t<1> Mock_Top_soc_dev__reset;
  dat_t<1> Mock_Top_soc_dev_seven_seg__reset;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_2_we;
  dat_t<1> Mock_Top_soc_dev_led__io_bus_we;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_2_sel;
  dat_t<1> Mock_Top_soc_dev_led__io_bus_sel;
  dat_t<1> Mock_Top_soc_dev_led__reset;
  dat_t<1> Mock_Top_soc_cpu__reset;
  dat_t<1> Mock_Top_soc_cpu_dpath__reset;
  dat_t<1> Mock_Top_soc_cpu_dpath_regfile__reset;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_ctrl_reg_we;
  dat_t<1> Mock_Top_soc_cpu_dpath__io_reg_we;
  dat_t<1> Mock_Top_soc_cpu_dpath_regfile__io_we;
  dat_t<1> T354;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_ctrl_inst_we;
  dat_t<1> Mock_Top_soc_cpu_dpath__io_inst_we;
  dat_t<1> Mock_Top_soc_cpu_dpath_alu__io_zero;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_ctrl_pc_we;
  dat_t<1> Mock_Top_soc_cpu_dpath__io_pc_we;
  dat_t<1> Mock_Top_soc_dev_ram_dev__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_ram_slave_ack;
  dat_t<1> Mock_Top_soc_dev_WB_Empty_Dev_2__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_7_ack;
  dat_t<1> Mock_Top_soc_dev_WB_Empty_Dev_1__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_6_ack;
  dat_t<1> Mock_Top_soc_dev_WB_Empty_Dev__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_5_ack;
  dat_t<1> Mock_Top_soc_dev_seven_seg__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_4_ack;
  dat_t<1> Mock_Top_soc_dev_counter__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_3_ack;
  dat_t<1> Mock_Top_soc_dev_led__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_2_ack;
  dat_t<1> Mock_Top_soc_dev_btn__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_1_ack;
  dat_t<1> Mock_Top_soc_dev_sw__io_bus_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_slaves_0_ack;
  dat_t<1> Mock_Top_soc_dev_bus__io_from_cpu_ack;
  dat_t<1> Mock_Top_soc_dev__io_bus_ack;
  dat_t<1> Mock_Top_soc_cpu__io_bus_ack;
  dat_t<1> Mock_Top_soc_cpu_cpath__io_bus_ack;
  dat_t<1> Mock_Top_soc_cpu_cpath__reset;
  dat_t<1> Mock_Top__io_devices_RAM_we;
  dat_t<1> T492;
  dat_t<2> Mock_Top_soc_cpu_cpath__io_ctrl_reg_we_src;
  dat_t<2> Mock_Top_soc_cpu_dpath__io_reg_we_src;
  dat_t<2> Mock_Top_soc_cpu_cpath__io_ctrl_reg_we_dst;
  dat_t<2> Mock_Top_soc_cpu_dpath__io_reg_we_dst;
  dat_t<2> Mock_Top_soc_cpu_cpath__io_ctrl_pc_next_sel;
  dat_t<2> Mock_Top_soc_cpu_dpath__io_pc_next_sel;
  dat_t<3> Mock_Top_soc_cpu_cpath__io_ctrl_alu_op;
  dat_t<3> Mock_Top_soc_cpu_dpath__io_alu_op;
  dat_t<3> Mock_Top_soc_cpu_dpath_alu__io_alu_op;
  dat_t<5> Mock_Top_soc_cpu_dpath_regfile__io_addrb;
  dat_t<5> Mock_Top_soc_cpu_dpath_regfile__io_addra;
  dat_t<5> Mock_Top__io_devices_BTN;
  dat_t<5> Mock_Top_soc__io_devices_BTN;
  dat_t<5> Mock_Top_soc_dev__io_devices_BTN;
  dat_t<5> Mock_Top_soc_dev_btn__io_BTN;
  dat_t<5> Mock_Top_soc_cpu_dpath_regfile__io_wtaddr;
  dat_t<8> T207;
  dat_t<8> Mock_Top_soc_dev_led__led_data;
  dat_t<8> Mock_Top__io_devices_SW;
  dat_t<8> Mock_Top_soc__io_devices_SW;
  dat_t<8> Mock_Top_soc_dev__io_devices_SW;
  dat_t<8> Mock_Top_soc_dev_sw__io_SW;
  dat_t<8> Mock_Top_soc_dev_led__io_LED;
  dat_t<8> Mock_Top_soc_dev__io_devices_LED;
  dat_t<8> Mock_Top_soc__io_devices_LED;
  dat_t<8> Mock_Top__io_devices_LED;
  dat_t<10> Mock_Top_soc_dev_ram_dev__io_ram_addra;
  dat_t<10> Mock_Top_soc_dev__io_devices_RAM_addra;
  dat_t<10> Mock_Top_soc__io_devices_RAM_addra;
  dat_t<10> Mock_Top_ram__io_addra;
  dat_t<10> Mock_Top__io_devices_RAM_addra;
  dat_t<32> Mock_Top_soc_cpu_dpath_regfile__io_doutb;
  dat_t<32> Mock_Top_soc_cpu_dpath__io_data_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_ctrl_data_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_bus_dat2;
  dat_t<32> Mock_Top_soc_cpu__io_bus_dat2;
  dat_t<32> Mock_Top_soc_dev__io_bus_dat2;
  dat_t<32> Mock_Top_soc_dev_bus__io_from_cpu_dat2;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_4_dat2;
  dat_t<32> Mock_Top_soc_dev_seven_seg__io_bus_dat2;
  dat_t<32> Mock_Top_soc_cpu_dpath__io_pc_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_ctrl_pc_out;
  dat_t<32> Mock_Top_soc_cpu_dpath_alu__io_in_b;
  dat_t<32> Mock_Top_soc_cpu_dpath_regfile__io_douta;
  dat_t<32> Mock_Top_soc_cpu_dpath_alu__io_in_a;
  dat_t<32> Mock_Top_soc_cpu_dpath_alu__io_out;
  dat_t<32> Mock_Top_soc_cpu_dpath__io_alu_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_ctrl_alu_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_bus_addr;
  dat_t<32> Mock_Top_soc_cpu__io_bus_addr;
  dat_t<32> Mock_Top_soc_dev__io_bus_addr;
  dat_t<32> Mock_Top_soc_dev_bus__io_from_cpu_addr;
  dat_t<32> T183;
  dat_t<32> Mock_Top_soc_dev_seven_seg__data_out;
  dat_t<32> T185;
  dat_t<32> Mock_Top_soc_dev_seven_seg__disp_data;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_2_dat2;
  dat_t<32> Mock_Top_soc_dev_led__io_bus_dat2;
  dat_t<32> T203;
  dat_t<32> Mock_Top_soc_dev_led__data_out;
  dat_t<32> Mock_Top_soc_dev_bus__io_ram_slave_addr;
  dat_t<32> Mock_Top_soc_dev_ram_dev__io_bus_addr;
  dat_t<32> Mock_Top_ram__io_douta;
  dat_t<32> Mock_Top_soc__io_devices_RAM_douta;
  dat_t<32> Mock_Top_soc_dev__io_devices_RAM_douta;
  dat_t<32> Mock_Top_soc_dev_ram_dev__io_ram_douta;
  dat_t<32> Mock_Top_soc_dev_ram_dev__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_ram_slave_dat4;
  dat_t<32> Mock_Top_soc_dev_WB_Empty_Dev_2__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_7_dat4;
  dat_t<32> Mock_Top_soc_dev_WB_Empty_Dev_1__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_6_dat4;
  dat_t<32> Mock_Top_soc_dev_WB_Empty_Dev__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_5_dat4;
  dat_t<32> Mock_Top_soc_dev_seven_seg__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_4_dat4;
  dat_t<32> Mock_Top_soc_dev_counter__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_3_dat4;
  dat_t<32> Mock_Top_soc_dev_led__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_2_dat4;
  dat_t<32> Mock_Top_soc_dev_btn__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_1_dat4;
  dat_t<32> Mock_Top_soc_dev_sw__io_bus_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_slaves_0_dat4;
  dat_t<32> Mock_Top_soc_dev_bus__io_from_cpu_dat4;
  dat_t<32> Mock_Top_soc_dev__io_bus_dat4;
  dat_t<32> Mock_Top_soc_cpu__io_bus_dat4;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_bus_dat4;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_ctrl_bus_data;
  dat_t<32> Mock_Top_soc_cpu_dpath__io_bus_data;
  dat_t<32> Mock_Top_soc_cpu_dpath_regfile__io_wtdata;
  dat_t<32> T356;
  dat_t<32> Mock_Top_soc_cpu_dpath__inst_reg;
  dat_t<32> T415;
  dat_t<32> Mock_Top_soc_cpu_dpath__pc;
  dat_t<32> Mock_Top_soc_cpu_dpath__io_inst;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_ctrl_inst;
  dat_t<32> T490;
  dat_t<32> Mock_Top_soc_cpu_cpath__state;
  dat_t<32> Mock_Top_soc_dev_seven_seg__io_DISP_NUM;
  dat_t<32> Mock_Top_soc_dev__io_devices_DISP_NUM;
  dat_t<32> Mock_Top_soc__io_devices_DISP_NUM;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_debug_inst_out;
  dat_t<32> Mock_Top_soc_cpu__io_debug_inst_out;
  dat_t<32> Mock_Top_soc__io_debug_inst_out;
  dat_t<32> Mock_Top__io_debug_inst_out;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_debug_bus_addr;
  dat_t<32> Mock_Top_soc_cpu__io_debug_bus_addr;
  dat_t<32> Mock_Top_soc__io_debug_bus_addr;
  dat_t<32> Mock_Top__io_debug_bus_addr;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_debug_bus_dat2;
  dat_t<32> Mock_Top_soc_cpu__io_debug_bus_dat2;
  dat_t<32> Mock_Top_soc__io_debug_bus_dat2;
  dat_t<32> Mock_Top__io_debug_bus_dat2;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_debug_bus_dat4;
  dat_t<32> Mock_Top_soc_cpu__io_debug_bus_dat4;
  dat_t<32> Mock_Top_soc__io_debug_bus_dat4;
  dat_t<32> Mock_Top__io_debug_bus_dat4;
  dat_t<32> Mock_Top_soc_cpu_cpath__io_debug_pc_out;
  dat_t<32> Mock_Top_soc_cpu__io_debug_pc_out;
  dat_t<32> Mock_Top_soc__io_debug_pc_out;
  dat_t<32> Mock_Top__io_debug_pc_out;
  dat_t<32> Mock_Top__io_devices_DISP_NUM;
  dat_t<32> Mock_Top__io_devices_RAM_dina;
  dat_t<32> Mock_Top__io_devices_RAM_douta;
  dat_t<32> T493;
  dat_t<168> T494;
  mem_t<32,32> Mock_Top_soc_cpu_dpath_regfile__rf;
  int clk;
  int clk_cnt;

  void init ( val_t rand_init = 0 );
  void clock_lo ( dat_t<1> reset );
  void clock_hi ( dat_t<1> reset );
  int clock ( dat_t<1> reset );
  mod_t* clone();
  bool set_circuit_from(mod_t* src);
  void print ( FILE* f );
  void print ( std::ostream& s );
  void dump ( FILE* f, int t );
  void dump_init ( FILE* f );

};

class Mock_Top_api_t : public mod_api_t {
  void init_mapping_table();
};



#endif
