#ifndef __SOC__
#define __SOC__

#include "emulator.h"

class SOC_t : public mod_t {
 private:
  val_t __rand_seed;
  void __srand(val_t seed) { __rand_seed = seed; }
  val_t __rand_val() { return ::__rand_val(&__rand_seed); }
 public:
  dat_t<1> SOC_cpu_cpath__io_ctrl_alu_b_sel;
  dat_t<1> SOC_cpu_dpath__io_alu_b_sel;
  dat_t<1> SOC_cpu_cpath__io_bus_we;
  dat_t<1> SOC_cpu__io_bus_we;
  dat_t<1> SOC_dev__io_bus_we;
  dat_t<1> SOC_dev_bus__io_from_cpu_we;
  dat_t<1> SOC_dev_bus__io_slaves_4_we;
  dat_t<1> SOC_dev_seven_seg__io_bus_we;
  dat_t<1> SOC_cpu_cpath__io_bus_sel;
  dat_t<1> SOC_cpu__io_bus_sel;
  dat_t<1> SOC_dev__io_bus_sel;
  dat_t<1> SOC_dev_bus__io_from_cpu_sel;
  dat_t<1> SOC_dev_bus__io_slaves_4_sel;
  dat_t<1> SOC_dev_seven_seg__io_bus_sel;
  dat_t<1> reset;
  dat_t<1> SOC_dev__reset;
  dat_t<1> SOC_dev_seven_seg__reset;
  dat_t<1> SOC_dev_bus__io_slaves_2_we;
  dat_t<1> SOC_dev_led__io_bus_we;
  dat_t<1> SOC_dev_bus__io_slaves_2_sel;
  dat_t<1> SOC_dev_led__io_bus_sel;
  dat_t<1> SOC_dev_led__reset;
  dat_t<1> SOC_dev_bus__reset;
  dat_t<1> T208;
  dat_t<1> SOC_dev_bus__ack_out;
  dat_t<1> SOC_cpu_cpath__io_ctrl_reg_we;
  dat_t<1> SOC_cpu_dpath__io_reg_we;
  dat_t<1> SOC_cpu_dpath_regfile__io_we;
  dat_t<1> T369;
  dat_t<1> SOC_cpu_cpath__io_ctrl_inst_we;
  dat_t<1> SOC_cpu_dpath__io_inst_we;
  dat_t<1> SOC_cpu__reset;
  dat_t<1> SOC_cpu_dpath__reset;
  dat_t<1> SOC_cpu_dpath_alu__io_zero;
  dat_t<1> SOC_cpu_cpath__io_ctrl_pc_we;
  dat_t<1> SOC_cpu_dpath__io_pc_we;
  dat_t<1> SOC_dev_ram_dev__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_ram_slave_ack;
  dat_t<1> SOC_dev_WB_Empty_Dev_2__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_7_ack;
  dat_t<1> SOC_dev_WB_Empty_Dev_1__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_6_ack;
  dat_t<1> SOC_dev_WB_Empty_Dev__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_5_ack;
  dat_t<1> SOC_dev_seven_seg__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_4_ack;
  dat_t<1> SOC_dev_counter__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_3_ack;
  dat_t<1> SOC_dev_led__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_2_ack;
  dat_t<1> SOC_dev_btn__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_1_ack;
  dat_t<1> SOC_dev_sw__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_0_ack;
  dat_t<1> SOC_dev_bus__io_from_cpu_ack;
  dat_t<1> SOC_dev__io_bus_ack;
  dat_t<1> SOC_cpu__io_bus_ack;
  dat_t<1> SOC_cpu_cpath__io_bus_ack;
  dat_t<1> SOC_cpu_cpath__reset;
  dat_t<1> T507;
  dat_t<1> T510;
  dat_t<1> T511;
  dat_t<1> T513;
  dat_t<1> T514;
  dat_t<1> T516;
  dat_t<1> T517;
  dat_t<1> T519;
  dat_t<1> T520;
  dat_t<1> T522;
  dat_t<1> T523;
  dat_t<1> T525;
  dat_t<1> T526;
  dat_t<1> T528;
  dat_t<1> T531;
  dat_t<1> T533;
  dat_t<1> T536;
  dat_t<1> T539;
  dat_t<1> T542;
  dat_t<1> T545;
  dat_t<1> T548;
  dat_t<1> T551;
  dat_t<1> T554;
  dat_t<1> T555;
  dat_t<1> T556;
  dat_t<1> T557;
  dat_t<1> T562;
  dat_t<1> T564;
  dat_t<1> T565;
  dat_t<1> T567;
  dat_t<2> SOC_cpu_cpath__io_ctrl_reg_we_src;
  dat_t<2> SOC_cpu_dpath__io_reg_we_src;
  dat_t<2> SOC_cpu_cpath__io_ctrl_reg_we_dst;
  dat_t<2> SOC_cpu_dpath__io_reg_we_dst;
  dat_t<2> SOC_cpu_cpath__io_ctrl_pc_next_sel;
  dat_t<2> SOC_cpu_dpath__io_pc_next_sel;
  dat_t<2> T558;
  dat_t<2> T560;
  dat_t<2> T561;
  dat_t<2> T563;
  dat_t<3> SOC_cpu_cpath__io_ctrl_alu_op;
  dat_t<3> SOC_cpu_dpath__io_alu_op;
  dat_t<3> SOC_cpu_dpath_alu__io_alu_op;
  dat_t<3> T529;
  dat_t<3> T559;
  dat_t<4> SOC_dev__io_devices_AN;
  dat_t<4> SOC__io_devices_AN;
  dat_t<5> SOC_cpu_dpath_regfile__io_addrb;
  dat_t<5> SOC_cpu_dpath_regfile__io_addra;
  dat_t<5> SOC__io_devices_BTN;
  dat_t<5> SOC_dev__io_devices_BTN;
  dat_t<5> SOC_dev_btn__io_BTN;
  dat_t<5> SOC_cpu_dpath_regfile__io_wtaddr;
  dat_t<8> T207;
  dat_t<8> SOC_dev_led__led_data;
  dat_t<8> SOC__io_devices_SW;
  dat_t<8> SOC_dev__io_devices_SW;
  dat_t<8> SOC_dev_sw__io_SW;
  dat_t<8> SOC_dev_led__io_LED;
  dat_t<8> SOC_dev__io_devices_LED;
  dat_t<8> SOC__io_devices_LED;
  dat_t<8> SOC_dev__io_devices_SEGMENT;
  dat_t<8> SOC__io_devices_SEGMENT;
  dat_t<8> T577;
  dat_t<10> SOC_dev_ram_dev__io_ram_addra;
  dat_t<10> SOC_dev_ram__io_addra;
  dat_t<32> SOC_cpu_dpath_regfile__io_doutb;
  dat_t<32> SOC_cpu_dpath__io_data_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_data_out;
  dat_t<32> SOC_cpu_cpath__io_bus_dat2;
  dat_t<32> SOC_cpu__io_bus_dat2;
  dat_t<32> SOC_dev__io_bus_dat2;
  dat_t<32> SOC_dev_bus__io_from_cpu_dat2;
  dat_t<32> SOC_dev_bus__io_slaves_4_dat2;
  dat_t<32> SOC_dev_seven_seg__io_bus_dat2;
  dat_t<32> SOC_cpu_dpath__io_pc_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_pc_out;
  dat_t<32> SOC_cpu_dpath_alu__io_in_b;
  dat_t<32> SOC_cpu_dpath_regfile__io_douta;
  dat_t<32> SOC_cpu_dpath_alu__io_in_a;
  dat_t<32> SOC_cpu_dpath_alu__io_out;
  dat_t<32> SOC_cpu_dpath__io_alu_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_alu_out;
  dat_t<32> SOC_cpu_cpath__io_bus_addr;
  dat_t<32> SOC_cpu__io_bus_addr;
  dat_t<32> SOC_dev__io_bus_addr;
  dat_t<32> SOC_dev_bus__io_from_cpu_addr;
  dat_t<32> T183;
  dat_t<32> SOC_dev_seven_seg__data_out;
  dat_t<32> T185;
  dat_t<32> SOC_dev_seven_seg__disp_data;
  dat_t<32> SOC_dev_seven_seg__io_DISP_NUM;
  dat_t<32> SOC_dev_bus__io_slaves_2_dat2;
  dat_t<32> SOC_dev_led__io_bus_dat2;
  dat_t<32> T203;
  dat_t<32> SOC_dev_led__data_out;
  dat_t<32> SOC_dev_bus__io_ram_slave_addr;
  dat_t<32> SOC_dev_ram_dev__io_bus_addr;
  dat_t<32> SOC_dev_ram__io_douta;
  dat_t<32> SOC_dev_ram_dev__io_ram_douta;
  dat_t<32> SOC_dev_ram_dev__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_ram_slave_dat4;
  dat_t<32> SOC_dev_WB_Empty_Dev_2__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_7_dat4;
  dat_t<32> SOC_dev_WB_Empty_Dev_1__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_6_dat4;
  dat_t<32> SOC_dev_WB_Empty_Dev__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_5_dat4;
  dat_t<32> SOC_dev_seven_seg__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_4_dat4;
  dat_t<32> SOC_dev_counter__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_3_dat4;
  dat_t<32> SOC_dev_led__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_2_dat4;
  dat_t<32> SOC_dev_btn__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_1_dat4;
  dat_t<32> SOC_dev_sw__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_0_dat4;
  dat_t<32> SOC_dev_bus__io_from_cpu_dat4;
  dat_t<32> SOC_dev__io_bus_dat4;
  dat_t<32> SOC_cpu__io_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_ctrl_bus_data;
  dat_t<32> SOC_cpu_dpath__io_bus_data;
  dat_t<32> SOC_cpu_dpath_regfile__io_wtdata;
  dat_t<32> T371;
  dat_t<32> SOC_cpu_dpath__inst_reg;
  dat_t<32> T430;
  dat_t<32> SOC_cpu_dpath__pc;
  dat_t<32> SOC_cpu_dpath__io_inst;
  dat_t<32> SOC_cpu_cpath__io_ctrl_inst;
  dat_t<32> T505;
  dat_t<32> SOC_cpu_cpath__state;
  dat_t<32> SOC_cpu_cpath__io_debug_inst_out;
  dat_t<32> SOC_cpu__io_debug_inst_out;
  dat_t<32> SOC__io_debug_inst_out;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_addr;
  dat_t<32> SOC_cpu__io_debug_bus_addr;
  dat_t<32> SOC__io_debug_bus_addr;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_dat2;
  dat_t<32> SOC_cpu__io_debug_bus_dat2;
  dat_t<32> SOC__io_debug_bus_dat2;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_dat4;
  dat_t<32> SOC_cpu__io_debug_bus_dat4;
  dat_t<32> SOC__io_debug_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_debug_pc_out;
  dat_t<32> SOC_cpu__io_debug_pc_out;
  dat_t<32> SOC__io_debug_pc_out;
  dat_t<32> T508;
  dat_t<32> T534;
  dat_t<32> T537;
  dat_t<32> T540;
  dat_t<32> T543;
  dat_t<32> T546;
  dat_t<32> T549;
  dat_t<32> T552;
  dat_t<32> T568;
  dat_t<96> T570;
  dat_t<104> T571;
  dat_t<120> T572;
  dat_t<120> T574;
  dat_t<120> T575;
  dat_t<128> T573;
  dat_t<144> T584;
  dat_t<168> T586;
  dat_t<176> T576;
  dat_t<176> T578;
  dat_t<176> T583;
  dat_t<184> T569;
  dat_t<184> T579;
  dat_t<184> T580;
  dat_t<184> T581;
  dat_t<208> T582;
  dat_t<336> T585;
  mem_t<32,32> SOC_cpu_dpath_regfile__rf;
  int clk;
  int clk_cnt;

  void init ( val_t rand_init = 0 );
  void clock_lo ( dat_t<1> reset );
  void clock_hi ( dat_t<1> reset );
  int clock ( dat_t<1> reset );
  mod_t* clone();
  bool set_circuit_from(mod_t* src);
  void print ( FILE* f );
  void print ( std::ostream& s );
  void dump ( FILE* f, int t );
  void dump_init ( FILE* f );

};

class SOC_api_t : public mod_api_t {
  void init_mapping_table();
};



#endif
