#ifndef __SOC__
#define __SOC__

#include "emulator.h"

class SOC_t : public mod_t {
 private:
  val_t __rand_seed;
  void __srand(val_t seed) { __rand_seed = seed; }
  val_t __rand_val() { return ::__rand_val(&__rand_seed); }
 public:
  dat_t<1> reset;
  dat_t<1> SOC_dev__reset;
  dat_t<1> SOC_dev_vga_dev__reset;
  dat_t<1> SOC_dev_vga_dev_vga__reset;
  dat_t<1> SOC_cpu_cpath__io_ctrl_alu_b_sel;
  dat_t<1> SOC_cpu_dpath__io_alu_b_sel;
  dat_t<1> SOC_cpu_cpath__io_bus_we;
  dat_t<1> SOC_cpu__io_bus_we;
  dat_t<1> SOC_dev__io_bus_we;
  dat_t<1> SOC_dev_bus__io_from_cpu_we;
  dat_t<1> SOC_dev_bus__io_slaves_5_we;
  dat_t<1> SOC_dev_vga_dev__io_bus_we;
  dat_t<1> SOC_cpu_cpath__io_bus_sel;
  dat_t<1> SOC_cpu__io_bus_sel;
  dat_t<1> SOC_dev__io_bus_sel;
  dat_t<1> SOC_dev_bus__io_from_cpu_sel;
  dat_t<1> SOC_dev_bus__io_slaves_5_sel;
  dat_t<1> SOC_dev_vga_dev__io_bus_sel;
  dat_t<1> T203;
  dat_t<1> SOC_dev_bus__io_slaves_4_we;
  dat_t<1> SOC_dev_seven_seg__io_bus_we;
  dat_t<1> SOC_dev_bus__io_slaves_4_sel;
  dat_t<1> SOC_dev_seven_seg__io_bus_sel;
  dat_t<1> SOC_dev_seven_seg__reset;
  dat_t<1> SOC_dev_bus__io_slaves_2_we;
  dat_t<1> SOC_dev_led__io_bus_we;
  dat_t<1> SOC_dev_bus__io_slaves_2_sel;
  dat_t<1> SOC_dev_led__io_bus_sel;
  dat_t<1> SOC_dev_led__reset;
  dat_t<1> SOC_cpu__reset;
  dat_t<1> SOC_cpu_dpath__reset;
  dat_t<1> SOC_cpu_dpath_regfile__reset;
  dat_t<1> SOC_cpu_cpath__io_ctrl_reg_we;
  dat_t<1> SOC_cpu_dpath__io_reg_we;
  dat_t<1> SOC_cpu_dpath_regfile__io_we;
  dat_t<1> T384;
  dat_t<1> SOC_cpu_cpath__io_ctrl_inst_we;
  dat_t<1> SOC_cpu_dpath__io_inst_we;
  dat_t<1> SOC_cpu_dpath_alu__io_zero;
  dat_t<1> SOC_cpu_cpath__io_ctrl_pc_we;
  dat_t<1> SOC_cpu_dpath__io_pc_we;
  dat_t<1> SOC_dev_ram_dev__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_ram_slave_ack;
  dat_t<1> SOC_dev_WB_Empty_Dev_1__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_7_ack;
  dat_t<1> SOC_dev_WB_Empty_Dev__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_6_ack;
  dat_t<1> SOC_dev_vga_dev__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_5_ack;
  dat_t<1> SOC_dev_seven_seg__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_4_ack;
  dat_t<1> SOC_dev_counter__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_3_ack;
  dat_t<1> SOC_dev_led__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_2_ack;
  dat_t<1> SOC_dev_btn__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_1_ack;
  dat_t<1> SOC_dev_sw__io_bus_ack;
  dat_t<1> SOC_dev_bus__io_slaves_0_ack;
  dat_t<1> SOC_dev_bus__io_from_cpu_ack;
  dat_t<1> SOC_dev__io_bus_ack;
  dat_t<1> SOC_cpu__io_bus_ack;
  dat_t<1> SOC_cpu_cpath__io_bus_ack;
  dat_t<1> SOC_cpu_cpath__reset;
  dat_t<1> SOC_dev_vga_dev_vga__io_vga_hsync;
  dat_t<1> SOC_dev_vga_dev__io_vga_hsync;
  dat_t<1> SOC_dev__io_devices_VGA_hsync;
  dat_t<1> SOC__io_devices_VGA_hsync;
  dat_t<1> SOC_dev_vga_dev_vga__io_vga_vsync;
  dat_t<1> SOC_dev_vga_dev__io_vga_vsync;
  dat_t<1> SOC_dev__io_devices_VGA_vsync;
  dat_t<1> SOC__io_devices_VGA_vsync;
  dat_t<1> SOC_dev_bus__io_ram_slave_we;
  dat_t<1> SOC_dev_ram_dev__io_bus_we;
  dat_t<1> SOC_dev_bus__io_ram_slave_sel;
  dat_t<1> SOC_dev_ram_dev__io_bus_sel;
  dat_t<1> SOC_dev_ram_dev__io_ram_we;
  dat_t<1> SOC_dev__io_devices_RAM_we;
  dat_t<1> SOC__io_devices_RAM_we;
  dat_t<1> T668;
  dat_t<2> T4;
  dat_t<2> SOC_dev_vga_dev_vga__p_counter;
  dat_t<2> SOC_cpu_cpath__io_ctrl_reg_we_src;
  dat_t<2> SOC_cpu_dpath__io_reg_we_src;
  dat_t<2> SOC_cpu_cpath__io_ctrl_reg_we_dst;
  dat_t<2> SOC_cpu_dpath__io_reg_we_dst;
  dat_t<2> SOC_cpu_cpath__io_ctrl_pc_next_sel;
  dat_t<2> SOC_cpu_dpath__io_pc_next_sel;
  dat_t<2> SOC_dev_vga_dev_vga__io_vga_blue;
  dat_t<2> SOC_dev_vga_dev__io_vga_blue;
  dat_t<2> SOC_dev__io_devices_VGA_blue;
  dat_t<2> SOC__io_devices_VGA_blue;
  dat_t<3> SOC_cpu_cpath__io_ctrl_alu_op;
  dat_t<3> SOC_cpu_dpath__io_alu_op;
  dat_t<3> SOC_cpu_dpath_alu__io_alu_op;
  dat_t<3> SOC_dev_vga_dev_vga__io_vga_red;
  dat_t<3> SOC_dev_vga_dev__io_vga_red;
  dat_t<3> SOC_dev__io_devices_VGA_red;
  dat_t<3> SOC__io_devices_VGA_red;
  dat_t<3> SOC_dev_vga_dev_vga__io_vga_green;
  dat_t<3> SOC_dev_vga_dev__io_vga_green;
  dat_t<3> SOC_dev__io_devices_VGA_green;
  dat_t<3> SOC__io_devices_VGA_green;
  dat_t<5> SOC_cpu_dpath_regfile__io_addrb;
  dat_t<5> SOC_cpu_dpath_regfile__io_addra;
  dat_t<5> SOC__io_devices_BTN;
  dat_t<5> SOC_dev__io_devices_BTN;
  dat_t<5> SOC_dev_btn__io_BTN;
  dat_t<5> SOC_cpu_dpath_regfile__io_wtaddr;
  dat_t<8> T245;
  dat_t<8> SOC_dev_led__led_data;
  dat_t<8> SOC__io_devices_SW;
  dat_t<8> SOC_dev__io_devices_SW;
  dat_t<8> SOC_dev_sw__io_SW;
  dat_t<8> SOC_dev_led__io_LED;
  dat_t<8> SOC_dev__io_devices_LED;
  dat_t<8> SOC__io_devices_LED;
  dat_t<8> SOC_dev_vga_dev_font__io_data;
  dat_t<8> SOC_dev_vga_dev_vga__io_ctrl_color;
  dat_t<10> SOC_dev_ram_dev__io_ram_addra;
  dat_t<10> SOC_dev__io_devices_RAM_addra;
  dat_t<10> SOC__io_devices_RAM_addra;
  dat_t<12> T204;
  dat_t<12> SOC_dev_vga_dev_font__io_addr;
  dat_t<16> T24;
  dat_t<32> T13;
  dat_t<32> SOC_dev_vga_dev_vga__h_counter;
  dat_t<32> T21;
  dat_t<32> SOC_dev_vga_dev_vga__v_counter;
  dat_t<32> SOC_cpu_dpath_regfile__io_doutb;
  dat_t<32> SOC_cpu_dpath__io_data_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_data_out;
  dat_t<32> SOC_cpu_cpath__io_bus_dat2;
  dat_t<32> SOC_cpu__io_bus_dat2;
  dat_t<32> SOC_dev__io_bus_dat2;
  dat_t<32> SOC_dev_bus__io_from_cpu_dat2;
  dat_t<32> SOC_dev_bus__io_slaves_5_dat2;
  dat_t<32> SOC_dev_vga_dev__io_bus_dat2;
  dat_t<32> SOC_cpu_dpath__io_pc_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_pc_out;
  dat_t<32> SOC_cpu_dpath_alu__io_in_b;
  dat_t<32> SOC_cpu_dpath_regfile__io_douta;
  dat_t<32> SOC_cpu_dpath_alu__io_in_a;
  dat_t<32> SOC_cpu_dpath_alu__io_out;
  dat_t<32> SOC_cpu_dpath__io_alu_out;
  dat_t<32> SOC_cpu_cpath__io_ctrl_alu_out;
  dat_t<32> SOC_cpu_cpath__io_bus_addr;
  dat_t<32> SOC_cpu__io_bus_addr;
  dat_t<32> SOC_dev__io_bus_addr;
  dat_t<32> SOC_dev_bus__io_from_cpu_addr;
  dat_t<32> SOC_dev_bus__io_slaves_5_addr;
  dat_t<32> SOC_dev_vga_dev__io_bus_addr;
  dat_t<32> SOC_dev_bus__io_slaves_4_dat2;
  dat_t<32> SOC_dev_seven_seg__io_bus_dat2;
  dat_t<32> T221;
  dat_t<32> SOC_dev_seven_seg__data_out;
  dat_t<32> T223;
  dat_t<32> SOC_dev_seven_seg__disp_data;
  dat_t<32> SOC_dev_bus__io_slaves_2_dat2;
  dat_t<32> SOC_dev_led__io_bus_dat2;
  dat_t<32> T241;
  dat_t<32> SOC_dev_led__data_out;
  dat_t<32> SOC__io_devices_RAM_douta;
  dat_t<32> SOC_dev__io_devices_RAM_douta;
  dat_t<32> SOC_dev_ram_dev__io_ram_douta;
  dat_t<32> SOC_dev_bus__io_ram_slave_addr;
  dat_t<32> SOC_dev_ram_dev__io_bus_addr;
  dat_t<32> SOC_dev_ram_dev__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_ram_slave_dat4;
  dat_t<32> SOC_dev_WB_Empty_Dev_1__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_7_dat4;
  dat_t<32> SOC_dev_WB_Empty_Dev__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_6_dat4;
  dat_t<32> SOC_dev_vga_dev__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_5_dat4;
  dat_t<32> SOC_dev_seven_seg__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_4_dat4;
  dat_t<32> SOC_dev_counter__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_3_dat4;
  dat_t<32> SOC_dev_led__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_2_dat4;
  dat_t<32> SOC_dev_btn__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_1_dat4;
  dat_t<32> SOC_dev_sw__io_bus_dat4;
  dat_t<32> SOC_dev_bus__io_slaves_0_dat4;
  dat_t<32> SOC_dev_bus__io_from_cpu_dat4;
  dat_t<32> SOC_dev__io_bus_dat4;
  dat_t<32> SOC_cpu__io_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_ctrl_bus_data;
  dat_t<32> SOC_cpu_dpath__io_bus_data;
  dat_t<32> SOC_cpu_dpath_regfile__io_wtdata;
  dat_t<32> T386;
  dat_t<32> SOC_cpu_dpath__inst_reg;
  dat_t<32> T445;
  dat_t<32> SOC_cpu_dpath__pc;
  dat_t<32> SOC_cpu_dpath__io_inst;
  dat_t<32> SOC_cpu_cpath__io_ctrl_inst;
  dat_t<32> T520;
  dat_t<32> SOC_cpu_cpath__state;
  dat_t<32> SOC_dev_seven_seg__io_DISP_NUM;
  dat_t<32> SOC_dev__io_devices_DISP_NUM;
  dat_t<32> SOC__io_devices_DISP_NUM;
  dat_t<32> SOC_dev_vga_dev_vga__io_ctrl_x;
  dat_t<32> SOC_dev_vga_dev_vga__io_ctrl_y;
  dat_t<32> SOC_dev_bus__io_ram_slave_dat2;
  dat_t<32> SOC_dev_ram_dev__io_bus_dat2;
  dat_t<32> SOC_dev_ram_dev__io_ram_dina;
  dat_t<32> SOC_dev__io_devices_RAM_dina;
  dat_t<32> SOC__io_devices_RAM_dina;
  dat_t<32> SOC_cpu_cpath__io_debug_inst_out;
  dat_t<32> SOC_cpu__io_debug_inst_out;
  dat_t<32> SOC__io_debug_inst_out;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_addr;
  dat_t<32> SOC_cpu__io_debug_bus_addr;
  dat_t<32> SOC__io_debug_bus_addr;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_dat2;
  dat_t<32> SOC_cpu__io_debug_bus_dat2;
  dat_t<32> SOC__io_debug_bus_dat2;
  dat_t<32> SOC_cpu_cpath__io_debug_bus_dat4;
  dat_t<32> SOC_cpu__io_debug_bus_dat4;
  dat_t<32> SOC__io_debug_bus_dat4;
  dat_t<32> SOC_cpu_cpath__io_debug_pc_out;
  dat_t<32> SOC_cpu__io_debug_pc_out;
  dat_t<32> SOC__io_debug_pc_out;
  dat_t<32> T669;
  dat_t<168> T670;
  mem_t<16,2400> SOC_dev_vga_dev__vmem;
  mem_t<32,32> SOC_cpu_dpath_regfile__rf;
  int clk;
  int clk_cnt;

  void init ( val_t rand_init = 0 );
  void clock_lo ( dat_t<1> reset );
  void clock_hi ( dat_t<1> reset );
  int clock ( dat_t<1> reset );
  mod_t* clone();
  bool set_circuit_from(mod_t* src);
  void print ( FILE* f );
  void print ( std::ostream& s );
  void dump ( FILE* f, int t );
  void dump_init ( FILE* f );

};

class SOC_api_t : public mod_api_t {
  void init_mapping_table();
};



#endif
